# Site settings
title: Technobotts
description: >
  Archived webpage for the Technobotts robotics team
# baseurl: "/technobotts.info"
url: "https://technobotts.github.io"

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: "" # all files in the project
    values:
      layout: "default"
