<p>
	In the past, the team has had success in the FIRST Lego League, going to the
	FIRST World Festival in Atlanta to represent the UK twice, in 2007 and 2009.
</p>
<p>
	The competition is split into four different categories, each accounting for 25% of the total score: Robot Performance, a Technical Presentation, a Research Project, and Teamwork.
</p>
<section id="climate-connections">
	<h2>2008-2009: Climate Connections
		<a href="http://sawyourad.com/technobotts/">old site</a>
	</h2>
	<p>This is the final year we competed in FLL. We built a robot capable of achieving a perfect score, and became the first ever team to achieve a perfect score - 400 points - at the UK National finals. In addition, the robot did it with 20 seconds to spare! As a result, we qualified for the World Festival for a second time.</p>
	<p>The team came fourth in the world in robot performance, achieving a perfect score on the competition table in one of its runs, and won the first place trophy for Innovative Design.</p>
	<div class="object-box">
		<iframe width="480" height="360" src="http://www.youtube.com/embed/px7uAAr9gMM?rel=0&wmode=transparent" frameborder="0" allowfullscreen></iframe>
		<span class="caption">400 points in 130 seconds</span>
		<img src="/images/Trophy.png"/>
		<span class="caption">FLL Atlanta trophy</span>
		<img src="/images/FLL Robot.jpg"/>
		<span class="caption">The FLL robot</span>
		<img src="/images/Big Bang award.jpg"/>
		<span class="caption">The Highly commended award we won at the Big Bang Science fair</span>
		<img src="/images/Big Bang demo.jpg"/>
		<span class="caption">The team demo-ing at the Big Bang Science fair</span>
	</div>
	<p>You can see the development of the robot design <a href="/fll-2008-old">here</a></p>
</section>
<section id="power-puzzle">
	<h2>2007-2008: Power Puzzle
		<a href="http://sawyourad.com/technobotts/2007-8/">old site</a>
	</h2>
	<p>
		Our robot is nxt-based, and achieves a low centre of gravity from its nxt brick being mounted around one stud off the ground, with some extra weight on its base – the LEGO rechargeable battery. Conventionally, it uses two motors for drive. It also has a simple attachment bay on its other motor, which is geared down (25:9) to provide extra torque and reduce its speed, which we found was too high. We use this, as well as other areas of the robot, to attach a selection of attachments for the missions.</p>
	<p>
		A set of <a href="http://ldraw.org" target="_blank">LDraw</a> files detailing the construction of the robot can be found in <a href="Technobotts FLL09 CAD.zip">this zip file</a>.
	</p>
	<div class="object-box">
		<img src="/images/fll/power-puzzle/mission-0.png"/>
		<span class="caption">Program 1 - Solar Satellite
			<small>The robot is aimed by eye, drives out at full power towards the satellite, and bumps it.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-2.png"/>
		<span class="caption">Program 2 - Wave Turbine, Trees, & Truck Retrieval
			<small>The robot uses the wave turbine to contain the trees, and hooks the truck as it returns to base.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-0.png"/>
		<span class="caption">Program 3a - Car & Solar Panel
			<small>The robot pushes the car out on a wheeled skid to prevent friction from the rubber tyres on the car. The solar panel is encased in, but not attached to, a rubber hooky thing, and is delivered before the robot returns to base.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-0.png"/>
		<span class="caption">Program 3b - Truck to Parking Lot
			<small>The robot gives the truck a small push into the parking lot.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-4.png"/>
		<span class="caption">Program 4 - Corn and Uranium
			<small>The robot uses a large hook to scoop the corn, and then the uranium, before returning to base.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-5.png"/>
		<span class="caption">Program 5 - Oil Delivery & Coal
			<small>The robot pushes an oil barrel in a container to the farm, and then pushes the lever at the end of the rails with a long pole.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-0.png"/>
		<span class="caption">Program 6 - Dam
			<small>The robot is aimed toward the northern river, and simply drives out of base and back in again.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-7.png"/>
		<span class="caption">Program 7 - Grid Connection, Wind Turbines, & Power Plant Supply
			<small>	The robot pushes out a large container holding the wind turbines, the electicity lines and a scoop. The uranium and coal are placed in the scoop, and delivered to the power plant.</small>
		</span>
		
		<img src="/images/fll/power-puzzle/mission-0.png"/>
		<span class="caption">Program 8 - Oil Rig
			<small>The robot drives out with a basket, pushes down on the lever with a long pole, waits for the oil barrels to fall in, and returns to base.</small>
		</span>
	</div>
</section>
<section id="nanoquest">
	<h2>2006-2007: Nanoquest</h2>
	<p>This was the first year of the Technobotts. We scraped through the Essex regional heat, but then went on to win the robot performance rounds in the National Finals, soaring through with a 355 point run. This got us through to the Nano Quest World festival in Atlanta, where we placed 28th out of 104 teams from all over the world.</p>
</section>