<map name="sponsors">
	<area shape="circle"
		alt="ELRIG" title="European Laboratory Robotics Interest Group"
		coords="86,92,79" href="http://www.elrig.org" />
	<area shape="rect"
		alt="CSR" title="Cambridge Silicon Radio"
		coords="174,15,275,118" href="http://www.csr.com" />
	<area shape="rect"
		alt="Ziath" title="Ziath"
		coords="294,24,410,72" href="http://www.ziath.com" />
		
	<area shape="rect"
		alt="fluidX" title="fluidX"
		coords="25,180,139,240" href="http://www.fluidx.co.uk" />
	<area shape="circle"
		alt="Wildcat" title="Wildcat"
		coords="232,185,45" />
	<area shape="rect"
		alt="Bigneat" title="Bigneat"
		coords="323,133,410,253" href="http://www.bigneat.com" />
		
	<area shape="rect"
		alt="John Lewis" title="John Lewis"
		coords="17,256,206,302" href="http://www.johnlewis.com" />
	<area shape="rect"
		alt="Tecan" title="Tecan"
		coords="237,264,409,293" href="http://www.tecan.com" />
		
	<area shape="rect"
		alt="IOP" title="Institute of Physics"
		coords="17,313,406,352" href="http://www.iop.org/" />
		
	<area shape="rect"
		alt="Cedrex A/S" title="Cedrex"
		coords="18,365,161,410" href="http://www.cedrex.dk" />
	<area shape="rect"
		alt="Gratnells" title="Gratnells"
		coords="271,364,405,429" href="http://www.gratnells.com" />
</map>
<section id="rcj-2010" style="clear:both">
	<h2>RCJ 2010 Sponsors</h2>
	<div class="object-box right">
		<img src="/images/Sponsors 2010.png" usemap="#sponsors" width="430" height="435" alt="ELRIG, CSR, Ziath, fluidX, Wildcat, Bigneat, John Lewis, TECAN, IOP, Cedrex A/S, and Gratnells" />
	</div>

	<p>
		TechnoBotts are very grateful to their sponsors, without whom this trip to Singapore would not be possible. Thank you all for your generous assistance.
	</p>
	<ul class="bulleted">
		<li><a href="http://www.elrig.org/">ELRIG</a></li>
		<li><a href="http://www.csr.com/">CSR</a></li>
		<li><a href="http://www.ziath.com/">Ziath</a></li>
		<li><a href="http://www.fluidx.co.uk/">fluidX</a></li>
		<li><a href="">Wildcat</a></li>
		<li><a href="http://www.bigneat.com/">Bigneat</a></li>
		<li><a href="http://www.johnlewis.com/">John Lewis</a></li>
		<li><a href="http://www.tecan.com/">TECAN</a></li>
		<li><a href="http://www.iop.org/">Institute of Physics</a></li>
		<li><a href="http://www.cedrex.dk/">Cedrex A/S</a></li>
		<li><a href="http://www.gratnells.com/">Gratnells</a></li>
	</ul>
</section>
<section id="fll-2009" style="clear:both">
	<h2>FLL 2009 Sponsors</h2>
	<div class="object-box right">
		<img src="/images/Sponsors 2009.png" width="430" height="467" alt="ARM, CSR, Gratnells, Cambridge Cognition, Institute of Physics, Bottisham Parish Council, IEEE, IOP and The John Lewis Partnership" />
	</div>
	<p>
		In February, the Technobotts&sup3; qualified as the only team to represent the UK and Ireland in the World Finals in Atlanta Georgia. There, we competed against 83 teams from around the globe, in a (successful) attempt to bring back a trophy for the UK!</p>
	<p>
		The cost of representing the country was around &pound;6000 when flights, lodging, and entry fees were added together, and the Technobotts&sup3; are very grateful for all of the contributions we had towards the costs.</p>
	<ul class="bulleted">
		<li><a href="http://arm.com/">ARM</a></li>
		<li><a href="http://csr.com/">CSR</a></li>
		<li><a href="http://gratnells.com/">Gratnells</a></li>
		<li><a href="http://cantab.com/">Cambridge Cognition</a></li>
		<li><a href="http://iop.org/">Institute of Physics</a></li>
		<li><a href="http://bottishampc.org.uk/">Bottisham Parish Council</a></li>
		<li><a href="http://ieee.org/">IEEE</a></li>	
		<li><a href="http://johnlewispartnership.co.uk/">John Lewis Partnership</a>, who provided the robot kit for the team</li>
	</ul>
	<p>We couldn't have done it without them!</p>
</section>
<section id="fll-2007" style="clear:both">
	<h2>FLL 2007 Sponsors</h2>
	<ul class="bulleted">
		<li><a href="http://iop.org/">Institute of Physics</a></li>
		<li><a href="http://britishcouncil.org/">British Council<a/></li>
		<li><a href="http://microsoft.com/">Microsoft</a></li>
		<li><a href="http://ncipher.com/">nCipher<a/></li>
		<li><a href="http://arm.com/">ARM</a></li>
		<li><a href="http://cantab.com/">Cambridge Cognition</a></li>
		<li><a href="http://johnlewispartnership.co.uk/">John Lewis Partnerships</a></li>
		<li><a href="http://cambridgeshire.gov.uk/">Cambridgeshire County Council</a></li>
		<li>Setpoint Essex</li>
		<li><a href="http://bottishampc.org.uk/">Bottisham Parish Council</a></li>
		<li>Elizabeth March Foundation</li>
		<li><a href="http://litcham.org/">Litcham Parish Council</a></li>
	</ul>
</section>