<section style="clear:both">
	<h2>Robot design 1 - Synchro Drive</h2>
	<div class="object-box right">
		<img src="images/fll/climate-connections/synchro-1.gif" alt="Picture 1" />
		<span class="caption">Rendering of the prototype with POV-Ray</span>
		<img src="images/fll/climate-connections/synchro-2.jpg" alt="Picture 2" />
		<span class="caption">Bottom view of the mockup</span>
		<img src="images/fll/climate-connections/synchro-3.jpg" alt="Picture 3" />
		<span class="caption">Top view of the mockup</span>
	</div>
	<div style="overflow:hidden">
		<h3>Features</h3>
		<ul class="bulleted">
			<li>One motor for steering and one for turning</li>
			<li>Chassis remains in the same orientation while the robot turns </li>
			<li>High-ish ground clearance</li>
			<li>All-round bumper (not shown)</li>
		</ul>
		<h3>Pros</h3>
		<ul class="bulleted">
			<li>Accurate turning</li>
			<li>Accurate moving straight</li>
			<li>Motors do not need to synchronise, which would be more unreliable</li>
			<li>No caster to drag and reduce reliability</li>
		</ul>
		<h3>Cons</h3>
		<ul class="bulleted">
			<li>Only one motor's power in both turns and movement</li>
			<li>Lots of gears between which backlash occurs</li>
			<li>Unstable</li>
		</ul>
	</div>
</section>
<section style="clear:both">
	<h2>Robot design 2 - Omni-wheel caster</h2>
	<div class="object-box left">
		<img src="images/fll/climate-connections/omni-1.jpg" alt="Picture 1" />
		<span class="caption">Top view</span>
		<img src="images/fll/climate-connections/omni-2.jpg" alt="Picture 2" />	
		<span class="caption">Detail of wheel</span>
		<img src="images/fll/climate-connections/omni-3.jpg" alt="Picture 3" />
		<span class="caption">Light sensor arrangement</span>
	</div>
	<div style="overflow:hidden">
		<h3>Features</h3>
		<ul class="bulleted">
			<li>Omni directional caster wheel</li>
			<li>Large wheels</li>
			<li>Low COG</li>
			<li>2 light sensors</li>
			<li>Arm motor</li>
		</ul>
		<h3>Pros</h3>
		<ul class="bulleted">
			<li>Accurate moving straight</li>
			<li>Caster designed to eliminate unwanted friction</li>
			<li>Faster robot movement due to large wheels</li>
		</ul>
		<h3>Cons</h3>
		<ul class="bulleted">
			<li>Tests showed the turning was inaccurate, as the omni-wheel tried to move to one of 12 positions</li>
			<li>Difficult to attach an arm of any kind</li>
			<li>USB port obscured</li>
		</ul>
	</div>
</section>
<section style="clear:both">
	<h2>Robot design 3 - Cube</h2>
	<div class="object-box right">
		<img src="images/fll/climate-connections/cube-1.jpg" alt="Picture 1" />
		<span class="caption">Front view</span>
		<img src="images/fll/climate-connections/cube-2.jpg" alt="Picture 2" />	
		<span class="caption">Side view</span>
		<img src="images/fll/climate-connections/cube-3.jpg" alt="Picture 3" />
		<span class="caption">Rear view</span>
	</div>
	<div style="overflow:hidden">
		<h3>Features</h3>
		<ul class="bulleted">
			<li>Ball caster</li>
			<li>Large wheels</li>
			<li>Arm motor</li>
			<li>Vertically mounted motors</li>
		</ul>
		<h3>Pros</h3>
		<ul class="bulleted">
			<li>Ball caster causes far less erratic behavior than a conventional caster</li>
			<li><acronym title="Center of gravity">COG</acronym> is over the wheels, so friction on the caster is further reduced</li>
			<li>USB port accessible</li>
		</ul>
		<h3>Cons</h3>
		<ul class="bulleted">
			<li>Screen is at an inconvenient angle</li>
			<li>The robot &quot;rears&quot; up as it accelerates</li>
		</ul>
	</div>
</section>
<section style="clear:both">
	<h2>Robot design 4 - Forklift</h2>
	<div class="object-box left">
		<img src="images/fll/climate-connections/fork-1.jpg" alt="Picture 1" />
		<span class="caption">Front view</span>
		<img src="images/fll/climate-connections/fork-2.jpg" alt="Picture 2" />	
		<span class="caption">Details of arm</span>
		<img src="images/fll/climate-connections/fork-3.jpg" alt="Picture 3" />
		<span class="caption">Ball caster</span>
	</div>
	<div style="overflow:hidden">
		<h3>Features</h3>
		<ul class="bulleted">
			<li>Ball caster</li>
			<li>Large wheels</li>
			<li>Arm akin to a forklift</li>
			<li>Vertically mounted motors</li>
		</ul>
		<h3>Pros</h3>
		<ul class="bulleted">
			<li>Ball caster</li>
			<li><acronym title="Center of gravity">COG</acronym> is over the wheels again, but not so much that the robot tips over</li>
			<li>More stable than design 3</li>
		</ul>
		<h3>Cons</h3>
		<ul class="bulleted">
			<li>Too long for reasonable manoeuvrability</li>
		</ul>
	</div>
</section>
<section style="clear:both">
	<h2>Robot design 5 - Regional heat Final Design</h2>
	<div class="object-box right">
		<img src="images/fll/climate-connections/duxford-1.jpg" alt="Picture 1" />
		<span class="caption">Side view</span>
		<img src="images/fll/climate-connections/duxford-2.jpg" alt="Picture 2" />
		<span class="caption">Details of the ball caster</span>
		<img src="images/fll/climate-connections/duxford-3.jpg" alt="Picture 3" />
		<span class="caption">Top view</span>
	</div>
	<div style="overflow:hidden">
		<h3>Features</h3>
		<ul class="bulleted">
			<li>Easily interchangeable attachments</li>
			<li>2 touch sensors</li>
			<li>2 light sensors</li>
		</ul>
		<h3>Pros</h3>
		<ul class="bulleted">
			<li>Ball caster</li>
			<li>Stable</li>
			<li>Weight over wheels</li>
		</ul>
		<h3>Cons</h3>
		<ul class="bulleted">
			<li>Insufficiently rigid - needed some work</li>
			<li>Not as reliable when turning as it could have been</li>
			<li>Moves counter-intuitively</li>
		</ul>
	</div>
</section>
